option(NPB_IS_BUILD_MPI_BASELINE "Build the NPB-provided MPI baseline" ON)
option(NPB_IS_BUILD_LCI_OPENMP "Build the LCI+OpenMP implementation" ON)
set(NPB_CLASSES A B C D E CACHE STRING "NPB IS classes to build")

include(NPBConfig)
add_subdirectory(common)
if(NPB_IS_BUILD_MPI_BASELINE)
  add_subdirectory(mpi-baseline)
endif()
if(NPB_IS_BUILD_LCI_OPENMP)
  add_subdirectory(lci-openmp)
endif()
